2013-09-26, 16:54:46 | DEBUG: __main__.PeonOrderSystem.__init__ : Entering __init__
2013-09-26, 16:54:46 | INFO: Beginning Initialization
2013-09-26, 16:54:46 | DEBUG: peonordersystem.interface.UI.UI.__init__ : Entering __init__
2013-09-26, 16:54:47 | DEBUG: peonordersystem.interface.Orders.Orders.__init__ : Entering __init__
2013-09-26, 16:54:47 | DEBUG: peonordersystem.interface.Orders.Orders._load_data : Entering _load_data
2013-09-26, 16:54:47 | DEBUG: peonordersystem.interface.Orders.Orders._set_model : Entering _set_model
2013-09-26, 16:54:47 | DEBUG: peonordersystem.interface.Orders.Orders._set_model : Exiting _set_model
2013-09-26, 16:54:47 | DEBUG: peonordersystem.interface.Orders.Orders._load_data : Exiting _load_data
2013-09-26, 16:54:47 | DEBUG: peonordersystem.interface.Orders.Orders.__init__ : Exiting __init__
2013-09-26, 16:54:47 | DEBUG: peonordersystem.interface.UpcomingOrders.UpcomingOrders.__init__ : Entering __init__
2013-09-26, 16:54:47 | DEBUG: peonordersystem.interface.UpcomingOrders.UpcomingOrders._load_data : Entering _load_data
2013-09-26, 16:54:47 | DEBUG: peonordersystem.interface.UpcomingOrders.UpcomingOrders.add_order : Entering add_order
2013-09-26, 16:54:47 | DEBUG: peonordersystem.interface.UpcomingOrders.UpcomingOrders.add_order : Exiting add_order
2013-09-26, 16:54:47 | DEBUG: peonordersystem.interface.UpcomingOrders.UpcomingOrders._load_data : Exiting _load_data
2013-09-26, 16:54:47 | DEBUG: peonordersystem.interface.UpcomingOrders.UpcomingOrders.__init__ : Exiting __init__
2013-09-26, 16:54:47 | DEBUG: peonordersystem.interface.Editor.Editor.__init__ : Entering __init__
2013-09-26, 16:54:47 | DEBUG: peonordersystem.interface.Editor.Editor.__init__ : Exiting __init__
2013-09-26, 16:54:47 | DEBUG: peonordersystem.interface.UI.UI.__init__ : Exiting __init__
2013-09-26, 16:54:47 | INFO: End initialization
2013-09-26, 16:54:47 | DEBUG: __main__.PeonOrderSystem.__init__ : Exiting __init__
2013-09-26, 16:54:48 | DEBUG: __main__.PeonOrderSystem.table_button_clicked : Entering table_button_clicked
2013-09-26, 16:54:48 | DEBUG: peonordersystem.interface.UI.UI.table_button_clicked : Entering table_button_clicked
2013-09-26, 16:54:48 | DEBUG: peonordersystem.interface.Orders.Orders.set_current_table : Entering set_current_table
2013-09-26, 16:54:48 | DEBUG: peonordersystem.interface.Orders.Orders._set_model : Entering _set_model
2013-09-26, 16:54:48 | DEBUG: peonordersystem.interface.Orders.Orders._set_model : Exiting _set_model
2013-09-26, 16:54:48 | DEBUG: peonordersystem.interface.Orders.Orders.set_current_table : Exiting set_current_table
2013-09-26, 16:54:48 | DEBUG: peonordersystem.interface.UI.UI.table_button_clicked : Exiting table_button_clicked
2013-09-26, 16:54:48 | DEBUG: __main__.PeonOrderSystem.table_button_clicked : Exiting table_button_clicked
2013-09-26, 16:54:48 | DEBUG: __main__.PeonOrderSystem.menu_button_clicked : Entering menu_button_clicked
2013-09-26, 16:54:48 | DEBUG: peonordersystem.interface.UI.UI.menu_button_clicked : Entering menu_button_clicked
2013-09-26, 16:54:48 | DEBUG: peonordersystem.interface.Orders.Orders.add : Entering add
2013-09-26, 16:54:48 | DEBUG: peonordersystem.interface.Orders.Orders.add : Exiting add
2013-09-26, 16:54:48 | DEBUG: peonordersystem.interface.UI.UI.menu_button_clicked : Exiting menu_button_clicked
2013-09-26, 16:54:48 | DEBUG: __main__.PeonOrderSystem.menu_button_clicked : Exiting menu_button_clicked
2013-09-26, 16:54:49 | DEBUG: __main__.PeonOrderSystem.menu_button_clicked : Entering menu_button_clicked
2013-09-26, 16:54:49 | DEBUG: peonordersystem.interface.UI.UI.menu_button_clicked : Entering menu_button_clicked
2013-09-26, 16:54:49 | DEBUG: peonordersystem.interface.Orders.Orders.add : Entering add
2013-09-26, 16:54:49 | DEBUG: peonordersystem.interface.Orders.Orders.add : Exiting add
2013-09-26, 16:54:49 | DEBUG: peonordersystem.interface.UI.UI.menu_button_clicked : Exiting menu_button_clicked
2013-09-26, 16:54:49 | DEBUG: __main__.PeonOrderSystem.menu_button_clicked : Exiting menu_button_clicked
2013-09-26, 16:54:51 | DEBUG: __main__.PeonOrderSystem.confirm_order : Entering confirm_order
2013-09-26, 16:54:51 | DEBUG: peonordersystem.interface.UI.UI.confirm_order : Entering confirm_order
2013-09-26, 16:54:51 | DEBUG: peonordersystem.interface.Orders.Orders.get_current_order : Entering get_current_order
2013-09-26, 16:54:51 | DEBUG: peonordersystem.interface.Orders.Orders.get_current_order : Exiting get_current_order
2013-09-26, 16:54:51 | DEBUG: peonordersystem.interface.Editor.Editor.confirm_order : Entering confirm_order
2013-09-26, 16:54:51 | DEBUG: peonordersystem.interface.Editor.Editor.confirm : Entering confirm
2013-09-26, 16:54:52 | DEBUG: peonordersystem.interface.Editor.Editor.confirm : Exiting confirm
2013-09-26, 16:54:52 | DEBUG: peonordersystem.interface.Editor.Editor.confirm_order : Exiting confirm_order
2013-09-26, 16:54:52 | DEBUG: peonordersystem.interface.UI.UI.confirm_order : Exiting confirm_order
2013-09-26, 16:54:52 | DEBUG: __main__.PeonOrderSystem.confirm_order : Exiting confirm_order
2013-09-26, 16:54:55 | DEBUG: __main__.PeonOrderSystem.confirm_checkout : Entering confirm_checkout
2013-09-26, 16:54:55 | DEBUG: peonordersystem.interface.UI.UI.confirm_checkout : Entering confirm_checkout
2013-09-26, 16:54:55 | DEBUG: peonordersystem.interface.Orders.Orders.get_current_order : Entering get_current_order
2013-09-26, 16:54:55 | DEBUG: peonordersystem.interface.Orders.Orders.get_current_order : Exiting get_current_order
2013-09-26, 16:54:55 | DEBUG: peonordersystem.interface.Editor.Editor.checkout_order : Entering checkout_order
2013-09-26, 16:54:55 | DEBUG: peonordersystem.interface.Editor.Editor.confirm : Entering confirm
2013-09-26, 16:54:55 | ERROR: global name 'CheckOperations' is not defined
2013-09-26, 16:54:55 | ERROR: 
2013-09-26, 16:54:55 | ERROR: TRACEBACK
2013-09-26, 16:54:55 | ERROR: Traceback (most recent call last):
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/ErrorLogger.py", line 103, in log_wrapper
    return func(*args, **kwargs)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Editor.py", line 102, in confirm
    order_list)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 1042, in __init__
    dialog)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 695, in __init__
    dialog, default_size)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 125, in __init__
    self.dialog.content_box = self.generate_layout()
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 709, in generate_layout
    model = self.generate_model()
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 1096, in generate_model
    total = CheckOperations.get_total(self.order_list)
NameError: global name 'CheckOperations' is not defined

2013-09-26, 16:54:55 | ERROR: 
2013-09-26, 16:54:55 | ERROR:    Parameters: 
2013-09-26, 16:54:55 | ERROR:       type = <class 'peonordersystem.interface.Editor.Editor'>
2013-09-26, 16:54:55 | ERROR:       value = <peonordersystem.interface.Editor.Editor object at 0x8d257cc>
2013-09-26, 16:54:55 | ERROR: 
2013-09-26, 16:54:55 | ERROR:       type = <type 'list'>
2013-09-26, 16:54:55 | ERROR:       value = [{'_price': 8.95, 'confirmed': True, '_option_choices': {u'DINNER:SIDE RICE': 1.5, u'DINNER:BROWN RICE': 2.5, u'LUNCH:BROWN RICE': 1.0}, 'notes': '', 'editable': False, '_locked': True, '_name': u'CHILI BASIL PLATE', 'stars': 3, 'options': []}, {'_price': 10.95, 'confirmed': True, '_option_choices': {u'DINNER:SIDE RICE': 1.5, u'DINNER:BROWN RICE': 2.5, u'LUNCH:BROWN RICE': 1.0}, 'notes': '', 'editable': False, '_locked': True, '_name': u'SESAME HONEY BEEF', 'stars': 3, 'options': []}, {'_price': 8.95, 'confirmed': True, '_option_choices': {u'DINNER:SIDE RICE': 1.5, u'DINNER:BROWN RICE': 2.5, u'LUNCH:BROWN RICE': 1.0}, 'notes': '', 'editable': False, '_locked': True, '_name': u'HOUSE FRIED RICE', 'stars': 3, 'options': []}, {'_price': 8.95, 'confirmed': True, '_option_choices': {u'DINNER:SIDE RICE': 1.5, u'DINNER:BROWN RICE': 2.5, u'LUNCH:BROWN RICE': 1.0}, 'notes': '', 'editable': False, '_locked': True, '_name': u'ORANGE CHICKEN', 'stars': 3, 'options': []}, {'_price': 8.95, 'confirmed': True, '_option_choices': {u'DINNER:SIDE RICE': 1.5, u'DINNER:BROWN RICE': 2.5, u'LUNCH:BROWN RICE': 1.0}, 'notes': '', 'editable': False, '_locked': True, '_name': u'PANANG CURRY', 'stars': 3, 'options': []}, {'_price': 8.95, 'confirmed': True, '_option_choices': {u'DINNER:SIDE RICE': 1.5, u'DINNER:BROWN RICE': 2.5, u'LUNCH:BROWN RICE': 1.0}, 'notes': '', 'editable': False, '_locked': True, '_name': u'CASHEW NUT CHICKEN', 'stars': 3, 'options': []}, {'_price': 4.95, 'confirmed': True, '_option_choices': {u'SKAGIT STRAWBERRY': 0.0, u'VANILLA': 0.0, u'CLEARLY COCONUT': 0.0, u'GREEN TEA': 0.0, u'DECIDEDLY CHOCOLATE': 0.0, u'MAPLE NUT': 0.0, u'MINT CHIP': 0.0}, 'notes': '', 'editable': True, '_locked': False, '_name': u'ICE CREAM TWO SCOOPS', 'stars': 0, 'options': []}, {'_price': 3.95, 'confirmed': True, '_option_choices': {u'SKAGIT STRAWBERRY': 0.0, u'VANILLA': 0.0, u'CLEARLY COCONUT': 0.0, u'GREEN TEA': 0.0, u'DECIDEDLY CHOCOLATE': 0.0, u'MAPLE NUT': 0.0, u'MINT CHIP': 0.0}, 'notes': '', 'editable': True, '_locked': False, '_name': u'ICE CREAM ONE SCOOP', 'stars': 0, 'options': []}]
2013-09-26, 16:54:55 | ERROR: 
2013-09-26, 16:54:55 | ERROR:       type = <class 'abc.ABCMeta'>
2013-09-26, 16:54:55 | ERROR:       value = <class 'peonordersystem.interface.Dialog.CheckoutConfirmationDialog'>
2013-09-26, 16:54:55 | ERROR: 
2013-09-26, 16:54:55 | ERROR:       type = <type 'instancemethod'>
2013-09-26, 16:54:55 | ERROR:       value = <bound method PeonOrderSystem.checkout_confirm of <__main__.PeonOrderSystem object at 0x8cf130c>>
2013-09-26, 16:54:55 | ERROR: 
2013-09-26, 16:54:55 | DEBUG: peonordersystem.interface.Editor.Editor.confirm : Exiting confirm
2013-09-26, 16:54:55 | ERROR: global name 'CheckOperations' is not defined
2013-09-26, 16:54:55 | ERROR: 
2013-09-26, 16:54:55 | ERROR: TRACEBACK
2013-09-26, 16:54:55 | ERROR: Traceback (most recent call last):
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/ErrorLogger.py", line 103, in log_wrapper
    return func(*args, **kwargs)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Editor.py", line 135, in checkout_order
    confirm_function)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/ErrorLogger.py", line 103, in log_wrapper
    return func(*args, **kwargs)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Editor.py", line 102, in confirm
    order_list)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 1042, in __init__
    dialog)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 695, in __init__
    dialog, default_size)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 125, in __init__
    self.dialog.content_box = self.generate_layout()
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 709, in generate_layout
    model = self.generate_model()
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 1096, in generate_model
    total = CheckOperations.get_total(self.order_list)
NameError: global name 'CheckOperations' is not defined

2013-09-26, 16:54:55 | ERROR: 
2013-09-26, 16:54:55 | ERROR:    Parameters: 
2013-09-26, 16:54:55 | ERROR:       type = <class 'peonordersystem.interface.Editor.Editor'>
2013-09-26, 16:54:55 | ERROR:       value = <peonordersystem.interface.Editor.Editor object at 0x8d257cc>
2013-09-26, 16:54:55 | ERROR: 
2013-09-26, 16:54:55 | ERROR:       type = <type 'list'>
2013-09-26, 16:54:55 | ERROR:       value = [{'_price': 8.95, 'confirmed': True, '_option_choices': {u'DINNER:SIDE RICE': 1.5, u'DINNER:BROWN RICE': 2.5, u'LUNCH:BROWN RICE': 1.0}, 'notes': '', 'editable': False, '_locked': True, '_name': u'CHILI BASIL PLATE', 'stars': 3, 'options': []}, {'_price': 10.95, 'confirmed': True, '_option_choices': {u'DINNER:SIDE RICE': 1.5, u'DINNER:BROWN RICE': 2.5, u'LUNCH:BROWN RICE': 1.0}, 'notes': '', 'editable': False, '_locked': True, '_name': u'SESAME HONEY BEEF', 'stars': 3, 'options': []}, {'_price': 8.95, 'confirmed': True, '_option_choices': {u'DINNER:SIDE RICE': 1.5, u'DINNER:BROWN RICE': 2.5, u'LUNCH:BROWN RICE': 1.0}, 'notes': '', 'editable': False, '_locked': True, '_name': u'HOUSE FRIED RICE', 'stars': 3, 'options': []}, {'_price': 8.95, 'confirmed': True, '_option_choices': {u'DINNER:SIDE RICE': 1.5, u'DINNER:BROWN RICE': 2.5, u'LUNCH:BROWN RICE': 1.0}, 'notes': '', 'editable': False, '_locked': True, '_name': u'ORANGE CHICKEN', 'stars': 3, 'options': []}, {'_price': 8.95, 'confirmed': True, '_option_choices': {u'DINNER:SIDE RICE': 1.5, u'DINNER:BROWN RICE': 2.5, u'LUNCH:BROWN RICE': 1.0}, 'notes': '', 'editable': False, '_locked': True, '_name': u'PANANG CURRY', 'stars': 3, 'options': []}, {'_price': 8.95, 'confirmed': True, '_option_choices': {u'DINNER:SIDE RICE': 1.5, u'DINNER:BROWN RICE': 2.5, u'LUNCH:BROWN RICE': 1.0}, 'notes': '', 'editable': False, '_locked': True, '_name': u'CASHEW NUT CHICKEN', 'stars': 3, 'options': []}, {'_price': 4.95, 'confirmed': True, '_option_choices': {u'SKAGIT STRAWBERRY': 0.0, u'VANILLA': 0.0, u'CLEARLY COCONUT': 0.0, u'GREEN TEA': 0.0, u'DECIDEDLY CHOCOLATE': 0.0, u'MAPLE NUT': 0.0, u'MINT CHIP': 0.0}, 'notes': '', 'editable': True, '_locked': False, '_name': u'ICE CREAM TWO SCOOPS', 'stars': 0, 'options': []}, {'_price': 3.95, 'confirmed': True, '_option_choices': {u'SKAGIT STRAWBERRY': 0.0, u'VANILLA': 0.0, u'CLEARLY COCONUT': 0.0, u'GREEN TEA': 0.0, u'DECIDEDLY CHOCOLATE': 0.0, u'MAPLE NUT': 0.0, u'MINT CHIP': 0.0}, 'notes': '', 'editable': True, '_locked': False, '_name': u'ICE CREAM ONE SCOOP', 'stars': 0, 'options': []}]
2013-09-26, 16:54:55 | ERROR: 
2013-09-26, 16:54:55 | ERROR:       type = <type 'instancemethod'>
2013-09-26, 16:54:55 | ERROR:       value = <bound method PeonOrderSystem.checkout_confirm of <__main__.PeonOrderSystem object at 0x8cf130c>>
2013-09-26, 16:54:55 | ERROR: 
2013-09-26, 16:54:55 | DEBUG: peonordersystem.interface.Editor.Editor.checkout_order : Exiting checkout_order
2013-09-26, 16:54:55 | ERROR: global name 'CheckOperations' is not defined
2013-09-26, 16:54:55 | ERROR: 
2013-09-26, 16:54:55 | ERROR: TRACEBACK
2013-09-26, 16:54:55 | ERROR: Traceback (most recent call last):
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/ErrorLogger.py", line 103, in log_wrapper
    return func(*args, **kwargs)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/UI.py", line 214, in confirm_checkout
    self.editor.checkout_order(current_order, self.checkout_confirm)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/ErrorLogger.py", line 103, in log_wrapper
    return func(*args, **kwargs)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Editor.py", line 135, in checkout_order
    confirm_function)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/ErrorLogger.py", line 103, in log_wrapper
    return func(*args, **kwargs)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Editor.py", line 102, in confirm
    order_list)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 1042, in __init__
    dialog)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 695, in __init__
    dialog, default_size)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 125, in __init__
    self.dialog.content_box = self.generate_layout()
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 709, in generate_layout
    model = self.generate_model()
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 1096, in generate_model
    total = CheckOperations.get_total(self.order_list)
NameError: global name 'CheckOperations' is not defined

2013-09-26, 16:54:55 | ERROR: 
2013-09-26, 16:54:55 | ERROR:    Parameters: 
2013-09-26, 16:54:55 | ERROR:       type = <class '__main__.PeonOrderSystem'>
2013-09-26, 16:54:55 | ERROR:       value = <__main__.PeonOrderSystem object at 0x8cf130c>
2013-09-26, 16:54:55 | ERROR: 
2013-09-26, 16:54:55 | ERROR:       type = <class 'gi.overrides.Gtk.Button'>
2013-09-26, 16:54:55 | ERROR:       value = <Button object at 0x8e1c57c (GtkButton at 0x8d560b8)>
2013-09-26, 16:54:55 | ERROR: 
2013-09-26, 16:54:55 | DEBUG: peonordersystem.interface.UI.UI.confirm_checkout : Exiting confirm_checkout
2013-09-26, 16:54:55 | ERROR: global name 'CheckOperations' is not defined
2013-09-26, 16:54:55 | ERROR: 
2013-09-26, 16:54:55 | ERROR: TRACEBACK
2013-09-26, 16:54:55 | ERROR: Traceback (most recent call last):
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/ErrorLogger.py", line 103, in log_wrapper
    return func(*args, **kwargs)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/ErrorLogger.py", line 103, in log_wrapper
    return func(*args, **kwargs)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/UI.py", line 214, in confirm_checkout
    self.editor.checkout_order(current_order, self.checkout_confirm)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/ErrorLogger.py", line 103, in log_wrapper
    return func(*args, **kwargs)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Editor.py", line 135, in checkout_order
    confirm_function)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/ErrorLogger.py", line 103, in log_wrapper
    return func(*args, **kwargs)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Editor.py", line 102, in confirm
    order_list)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 1042, in __init__
    dialog)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 695, in __init__
    dialog, default_size)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 125, in __init__
    self.dialog.content_box = self.generate_layout()
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 709, in generate_layout
    model = self.generate_model()
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 1096, in generate_model
    total = CheckOperations.get_total(self.order_list)
NameError: global name 'CheckOperations' is not defined

2013-09-26, 16:54:55 | ERROR: 
2013-09-26, 16:54:55 | ERROR:    Parameters: 
2013-09-26, 16:54:55 | ERROR:       type = <class '__main__.PeonOrderSystem'>
2013-09-26, 16:54:55 | ERROR:       value = <__main__.PeonOrderSystem object at 0x8cf130c>
2013-09-26, 16:54:55 | ERROR: 
2013-09-26, 16:54:55 | ERROR:       type = <class 'gi.overrides.Gtk.Button'>
2013-09-26, 16:54:55 | ERROR:       value = <Button object at 0x8e1c57c (GtkButton at 0x8d560b8)>
2013-09-26, 16:54:55 | ERROR: 
2013-09-26, 16:54:55 | DEBUG: __main__.PeonOrderSystem.confirm_checkout : Exiting confirm_checkout
2013-09-26, 16:54:56 | DEBUG: __main__.PeonOrderSystem.confirm_checkout : Entering confirm_checkout
2013-09-26, 16:54:56 | DEBUG: peonordersystem.interface.UI.UI.confirm_checkout : Entering confirm_checkout
2013-09-26, 16:54:56 | DEBUG: peonordersystem.interface.Orders.Orders.get_current_order : Entering get_current_order
2013-09-26, 16:54:56 | DEBUG: peonordersystem.interface.Orders.Orders.get_current_order : Exiting get_current_order
2013-09-26, 16:54:56 | DEBUG: peonordersystem.interface.Editor.Editor.checkout_order : Entering checkout_order
2013-09-26, 16:54:56 | DEBUG: peonordersystem.interface.Editor.Editor.confirm : Entering confirm
2013-09-26, 16:54:56 | ERROR: global name 'CheckOperations' is not defined
2013-09-26, 16:54:56 | ERROR: 
2013-09-26, 16:54:56 | ERROR: TRACEBACK
2013-09-26, 16:54:56 | ERROR: Traceback (most recent call last):
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/ErrorLogger.py", line 103, in log_wrapper
    return func(*args, **kwargs)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Editor.py", line 102, in confirm
    order_list)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 1042, in __init__
    dialog)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 695, in __init__
    dialog, default_size)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 125, in __init__
    self.dialog.content_box = self.generate_layout()
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 709, in generate_layout
    model = self.generate_model()
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 1096, in generate_model
    total = CheckOperations.get_total(self.order_list)
NameError: global name 'CheckOperations' is not defined

2013-09-26, 16:54:56 | ERROR: 
2013-09-26, 16:54:56 | ERROR:    Parameters: 
2013-09-26, 16:54:56 | ERROR:       type = <class 'peonordersystem.interface.Editor.Editor'>
2013-09-26, 16:54:56 | ERROR:       value = <peonordersystem.interface.Editor.Editor object at 0x8d257cc>
2013-09-26, 16:54:56 | ERROR: 
2013-09-26, 16:54:56 | ERROR:       type = <type 'list'>
2013-09-26, 16:54:56 | ERROR:       value = [{'_price': 8.95, 'confirmed': True, '_option_choices': {u'DINNER:SIDE RICE': 1.5, u'DINNER:BROWN RICE': 2.5, u'LUNCH:BROWN RICE': 1.0}, 'notes': '', 'editable': False, '_locked': True, '_name': u'CHILI BASIL PLATE', 'stars': 3, 'options': []}, {'_price': 10.95, 'confirmed': True, '_option_choices': {u'DINNER:SIDE RICE': 1.5, u'DINNER:BROWN RICE': 2.5, u'LUNCH:BROWN RICE': 1.0}, 'notes': '', 'editable': False, '_locked': True, '_name': u'SESAME HONEY BEEF', 'stars': 3, 'options': []}, {'_price': 8.95, 'confirmed': True, '_option_choices': {u'DINNER:SIDE RICE': 1.5, u'DINNER:BROWN RICE': 2.5, u'LUNCH:BROWN RICE': 1.0}, 'notes': '', 'editable': False, '_locked': True, '_name': u'HOUSE FRIED RICE', 'stars': 3, 'options': []}, {'_price': 8.95, 'confirmed': True, '_option_choices': {u'DINNER:SIDE RICE': 1.5, u'DINNER:BROWN RICE': 2.5, u'LUNCH:BROWN RICE': 1.0}, 'notes': '', 'editable': False, '_locked': True, '_name': u'ORANGE CHICKEN', 'stars': 3, 'options': []}, {'_price': 8.95, 'confirmed': True, '_option_choices': {u'DINNER:SIDE RICE': 1.5, u'DINNER:BROWN RICE': 2.5, u'LUNCH:BROWN RICE': 1.0}, 'notes': '', 'editable': False, '_locked': True, '_name': u'PANANG CURRY', 'stars': 3, 'options': []}, {'_price': 8.95, 'confirmed': True, '_option_choices': {u'DINNER:SIDE RICE': 1.5, u'DINNER:BROWN RICE': 2.5, u'LUNCH:BROWN RICE': 1.0}, 'notes': '', 'editable': False, '_locked': True, '_name': u'CASHEW NUT CHICKEN', 'stars': 3, 'options': []}, {'_price': 4.95, 'confirmed': True, '_option_choices': {u'SKAGIT STRAWBERRY': 0.0, u'VANILLA': 0.0, u'CLEARLY COCONUT': 0.0, u'GREEN TEA': 0.0, u'DECIDEDLY CHOCOLATE': 0.0, u'MAPLE NUT': 0.0, u'MINT CHIP': 0.0}, 'notes': '', 'editable': True, '_locked': False, '_name': u'ICE CREAM TWO SCOOPS', 'stars': 0, 'options': []}, {'_price': 3.95, 'confirmed': True, '_option_choices': {u'SKAGIT STRAWBERRY': 0.0, u'VANILLA': 0.0, u'CLEARLY COCONUT': 0.0, u'GREEN TEA': 0.0, u'DECIDEDLY CHOCOLATE': 0.0, u'MAPLE NUT': 0.0, u'MINT CHIP': 0.0}, 'notes': '', 'editable': True, '_locked': False, '_name': u'ICE CREAM ONE SCOOP', 'stars': 0, 'options': []}]
2013-09-26, 16:54:56 | ERROR: 
2013-09-26, 16:54:56 | ERROR:       type = <class 'abc.ABCMeta'>
2013-09-26, 16:54:56 | ERROR:       value = <class 'peonordersystem.interface.Dialog.CheckoutConfirmationDialog'>
2013-09-26, 16:54:56 | ERROR: 
2013-09-26, 16:54:56 | ERROR:       type = <type 'instancemethod'>
2013-09-26, 16:54:56 | ERROR:       value = <bound method PeonOrderSystem.checkout_confirm of <__main__.PeonOrderSystem object at 0x8cf130c>>
2013-09-26, 16:54:56 | ERROR: 
2013-09-26, 16:54:56 | DEBUG: peonordersystem.interface.Editor.Editor.confirm : Exiting confirm
2013-09-26, 16:54:56 | ERROR: global name 'CheckOperations' is not defined
2013-09-26, 16:54:56 | ERROR: 
2013-09-26, 16:54:56 | ERROR: TRACEBACK
2013-09-26, 16:54:56 | ERROR: Traceback (most recent call last):
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/ErrorLogger.py", line 103, in log_wrapper
    return func(*args, **kwargs)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Editor.py", line 135, in checkout_order
    confirm_function)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/ErrorLogger.py", line 103, in log_wrapper
    return func(*args, **kwargs)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Editor.py", line 102, in confirm
    order_list)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 1042, in __init__
    dialog)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 695, in __init__
    dialog, default_size)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 125, in __init__
    self.dialog.content_box = self.generate_layout()
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 709, in generate_layout
    model = self.generate_model()
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 1096, in generate_model
    total = CheckOperations.get_total(self.order_list)
NameError: global name 'CheckOperations' is not defined

2013-09-26, 16:54:56 | ERROR: 
2013-09-26, 16:54:56 | ERROR:    Parameters: 
2013-09-26, 16:54:56 | ERROR:       type = <class 'peonordersystem.interface.Editor.Editor'>
2013-09-26, 16:54:56 | ERROR:       value = <peonordersystem.interface.Editor.Editor object at 0x8d257cc>
2013-09-26, 16:54:56 | ERROR: 
2013-09-26, 16:54:56 | ERROR:       type = <type 'list'>
2013-09-26, 16:54:56 | ERROR:       value = [{'_price': 8.95, 'confirmed': True, '_option_choices': {u'DINNER:SIDE RICE': 1.5, u'DINNER:BROWN RICE': 2.5, u'LUNCH:BROWN RICE': 1.0}, 'notes': '', 'editable': False, '_locked': True, '_name': u'CHILI BASIL PLATE', 'stars': 3, 'options': []}, {'_price': 10.95, 'confirmed': True, '_option_choices': {u'DINNER:SIDE RICE': 1.5, u'DINNER:BROWN RICE': 2.5, u'LUNCH:BROWN RICE': 1.0}, 'notes': '', 'editable': False, '_locked': True, '_name': u'SESAME HONEY BEEF', 'stars': 3, 'options': []}, {'_price': 8.95, 'confirmed': True, '_option_choices': {u'DINNER:SIDE RICE': 1.5, u'DINNER:BROWN RICE': 2.5, u'LUNCH:BROWN RICE': 1.0}, 'notes': '', 'editable': False, '_locked': True, '_name': u'HOUSE FRIED RICE', 'stars': 3, 'options': []}, {'_price': 8.95, 'confirmed': True, '_option_choices': {u'DINNER:SIDE RICE': 1.5, u'DINNER:BROWN RICE': 2.5, u'LUNCH:BROWN RICE': 1.0}, 'notes': '', 'editable': False, '_locked': True, '_name': u'ORANGE CHICKEN', 'stars': 3, 'options': []}, {'_price': 8.95, 'confirmed': True, '_option_choices': {u'DINNER:SIDE RICE': 1.5, u'DINNER:BROWN RICE': 2.5, u'LUNCH:BROWN RICE': 1.0}, 'notes': '', 'editable': False, '_locked': True, '_name': u'PANANG CURRY', 'stars': 3, 'options': []}, {'_price': 8.95, 'confirmed': True, '_option_choices': {u'DINNER:SIDE RICE': 1.5, u'DINNER:BROWN RICE': 2.5, u'LUNCH:BROWN RICE': 1.0}, 'notes': '', 'editable': False, '_locked': True, '_name': u'CASHEW NUT CHICKEN', 'stars': 3, 'options': []}, {'_price': 4.95, 'confirmed': True, '_option_choices': {u'SKAGIT STRAWBERRY': 0.0, u'VANILLA': 0.0, u'CLEARLY COCONUT': 0.0, u'GREEN TEA': 0.0, u'DECIDEDLY CHOCOLATE': 0.0, u'MAPLE NUT': 0.0, u'MINT CHIP': 0.0}, 'notes': '', 'editable': True, '_locked': False, '_name': u'ICE CREAM TWO SCOOPS', 'stars': 0, 'options': []}, {'_price': 3.95, 'confirmed': True, '_option_choices': {u'SKAGIT STRAWBERRY': 0.0, u'VANILLA': 0.0, u'CLEARLY COCONUT': 0.0, u'GREEN TEA': 0.0, u'DECIDEDLY CHOCOLATE': 0.0, u'MAPLE NUT': 0.0, u'MINT CHIP': 0.0}, 'notes': '', 'editable': True, '_locked': False, '_name': u'ICE CREAM ONE SCOOP', 'stars': 0, 'options': []}]
2013-09-26, 16:54:56 | ERROR: 
2013-09-26, 16:54:56 | ERROR:       type = <type 'instancemethod'>
2013-09-26, 16:54:56 | ERROR:       value = <bound method PeonOrderSystem.checkout_confirm of <__main__.PeonOrderSystem object at 0x8cf130c>>
2013-09-26, 16:54:56 | ERROR: 
2013-09-26, 16:54:56 | DEBUG: peonordersystem.interface.Editor.Editor.checkout_order : Exiting checkout_order
2013-09-26, 16:54:56 | ERROR: global name 'CheckOperations' is not defined
2013-09-26, 16:54:56 | ERROR: 
2013-09-26, 16:54:56 | ERROR: TRACEBACK
2013-09-26, 16:54:56 | ERROR: Traceback (most recent call last):
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/ErrorLogger.py", line 103, in log_wrapper
    return func(*args, **kwargs)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/UI.py", line 214, in confirm_checkout
    self.editor.checkout_order(current_order, self.checkout_confirm)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/ErrorLogger.py", line 103, in log_wrapper
    return func(*args, **kwargs)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Editor.py", line 135, in checkout_order
    confirm_function)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/ErrorLogger.py", line 103, in log_wrapper
    return func(*args, **kwargs)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Editor.py", line 102, in confirm
    order_list)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 1042, in __init__
    dialog)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 695, in __init__
    dialog, default_size)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 125, in __init__
    self.dialog.content_box = self.generate_layout()
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 709, in generate_layout
    model = self.generate_model()
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 1096, in generate_model
    total = CheckOperations.get_total(self.order_list)
NameError: global name 'CheckOperations' is not defined

2013-09-26, 16:54:56 | ERROR: 
2013-09-26, 16:54:56 | ERROR:    Parameters: 
2013-09-26, 16:54:56 | ERROR:       type = <class '__main__.PeonOrderSystem'>
2013-09-26, 16:54:56 | ERROR:       value = <__main__.PeonOrderSystem object at 0x8cf130c>
2013-09-26, 16:54:56 | ERROR: 
2013-09-26, 16:54:56 | ERROR:       type = <class 'gi.overrides.Gtk.Button'>
2013-09-26, 16:54:56 | ERROR:       value = <Button object at 0x8e1c57c (GtkButton at 0x8d560b8)>
2013-09-26, 16:54:56 | ERROR: 
2013-09-26, 16:54:56 | DEBUG: peonordersystem.interface.UI.UI.confirm_checkout : Exiting confirm_checkout
2013-09-26, 16:54:56 | ERROR: global name 'CheckOperations' is not defined
2013-09-26, 16:54:56 | ERROR: 
2013-09-26, 16:54:56 | ERROR: TRACEBACK
2013-09-26, 16:54:56 | ERROR: Traceback (most recent call last):
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/ErrorLogger.py", line 103, in log_wrapper
    return func(*args, **kwargs)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/ErrorLogger.py", line 103, in log_wrapper
    return func(*args, **kwargs)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/UI.py", line 214, in confirm_checkout
    self.editor.checkout_order(current_order, self.checkout_confirm)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/ErrorLogger.py", line 103, in log_wrapper
    return func(*args, **kwargs)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Editor.py", line 135, in checkout_order
    confirm_function)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/ErrorLogger.py", line 103, in log_wrapper
    return func(*args, **kwargs)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Editor.py", line 102, in confirm
    order_list)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 1042, in __init__
    dialog)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 695, in __init__
    dialog, default_size)
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 125, in __init__
    self.dialog.content_box = self.generate_layout()
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 709, in generate_layout
    model = self.generate_model()
  File "/home/carl-m/workspace/PeonOrderSystem/PeonOrderSystem/peonordersystem/interface/Dialog.py", line 1096, in generate_model
    total = CheckOperations.get_total(self.order_list)
NameError: global name 'CheckOperations' is not defined

2013-09-26, 16:54:56 | ERROR: 
2013-09-26, 16:54:56 | ERROR:    Parameters: 
2013-09-26, 16:54:56 | ERROR:       type = <class '__main__.PeonOrderSystem'>
2013-09-26, 16:54:56 | ERROR:       value = <__main__.PeonOrderSystem object at 0x8cf130c>
2013-09-26, 16:54:56 | ERROR: 
2013-09-26, 16:54:56 | ERROR:       type = <class 'gi.overrides.Gtk.Button'>
2013-09-26, 16:54:56 | ERROR:       value = <Button object at 0x8e1c57c (GtkButton at 0x8d560b8)>
2013-09-26, 16:54:56 | ERROR: 
2013-09-26, 16:54:56 | DEBUG: __main__.PeonOrderSystem.confirm_checkout : Exiting confirm_checkout
